# Generated by Django 3.1.3 on 2020-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('staff', 'staff'), ('patient', 'patient')], default='admin', max_length=30),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='users.Specialization'),
        ),
    ]
