# Generated by Django 3.1.3 on 2020-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201229_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
