# Generated by Django 3.1.3 on 2020-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201230_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(default='Aut maiores voluptates amet et quis praesentium qui senda para'),
        ),
    ]
