# Generated by Django 3.1.3 on 2020-12-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=15),
        ),
    ]
